name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'static/**'
      - 'package-lock.json'
      - 'svelte.config.js'
      - 'vite.config.ts'
      - 'tsconfig.json'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Cache Node Modules 💾
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
